"""
Distillation data generation — calls Claude (teacher) to produce training samples
for the student model (Qwen3.5-0.8B).

Reads:
  data/jds/all_jds.jsonl          — generated by scripts/generate_jds.py
  data/resumes/all_resumes.jsonl  — generated by scripts/generate_resumes.py (optional)

Writes:
  data/generated/train_raw.jsonl  — raw teacher outputs, one sample per line

Usage:
  # Query parsing only (requires JDs)
  python scripts/distill_data.py --tasks query_parsing --num 1500

  # Both tasks (requires JDs + resumes)
  python scripts/distill_data.py --tasks query_parsing,match_explanation --num 1500

  # Resume from a previous interrupted run
  python scripts/distill_data.py --tasks query_parsing --num 1500 --resume

  # Use Batch API for 50% cost reduction (async, takes ~1hr)
  python scripts/distill_data.py --tasks query_parsing --num 1500 --batch
"""

import anthropic
import argparse
import json
import os
import random
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

# Make src importable when running from project root
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from prompts import (
    build_query_parser_prompt,
    build_match_explainer_prompt,
    format_training_sample,
    get_inference_messages,
)

load_dotenv()

MODEL = "claude-sonnet-4-6"
OUTPUT_PATH = Path("data/generated/train_raw.jsonl")


# ---------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------

def load_jds(path: str = "data/jds/all_jds.jsonl") -> list[dict]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"{path} not found. Run scripts/generate_jds.py first."
        )
    with open(p) as f:
        return [json.loads(line) for line in f if line.strip()]


def load_resumes(path: str = "data/resumes/all_resumes.jsonl") -> list[dict]:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"{path} not found. Run scripts/generate_resumes.py first."
        )
    with open(p) as f:
        return [json.loads(line) for line in f if line.strip()]


def load_existing_ids(output_path: Path) -> set[str]:
    """Return set of sample IDs already written — for resuming interrupted runs."""
    if not output_path.exists():
        return set()
    ids = set()
    with open(output_path) as f:
        for line in f:
            if line.strip():
                try:
                    ids.add(json.loads(line)["id"])
                except (json.JSONDecodeError, KeyError):
                    pass
    return ids


# ---------------------------------------------------------------
# Standard (synchronous) generation
# ---------------------------------------------------------------

def call_claude(client: anthropic.Anthropic, messages: list[dict]) -> str:
    # Claude API requires system as a top-level param, not in messages
    system = None
    filtered = []
    for msg in messages:
        if msg["role"] == "system":
            system = msg["content"]
        else:
            filtered.append(msg)

    kwargs = {"model": MODEL, "max_tokens": 1024, "messages": filtered}
    if system:
        kwargs["system"] = system

    response = client.messages.create(**kwargs)
    return response.content[0].text.strip()


def run_standard(
    client: anthropic.Anthropic,
    tasks: list[str],
    jds: list[dict],
    resumes: list[dict],
    num_per_task: int,
    existing_ids: set[str],
    output_path: Path,
    delay: float,
):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    generated = 0
    failed = 0

    with open(output_path, "a") as out_f:
        for task in tasks:
            print(f"\n--- Task: {task} (target: {num_per_task} samples) ---")
            count = 0

            if task == "query_parsing":
                items = random.sample(jds, min(num_per_task, len(jds)))
                if len(items) < num_per_task:
                    # Sample with replacement if we need more than available
                    items += random.choices(jds, k=num_per_task - len(items))

                for i, jd in enumerate(items):
                    sample_id = f"qp_{jd['id']}_{i:04d}"
                    if sample_id in existing_ids:
                        print(f"  [{i+1}/{num_per_task}] {sample_id} — skip (exists)")
                        count += 1
                        continue

                    user_content = build_query_parser_prompt(jd["text"])
                    messages = get_inference_messages("query_parsing", user_content)

                    try:
                        output = call_claude(client, messages)
                        # Validate JSON
                        json.loads(output)
                    except json.JSONDecodeError:
                        print(f"  [{i+1}/{num_per_task}] {sample_id} — SKIP (invalid JSON)")
                        failed += 1
                        time.sleep(delay)
                        continue
                    except Exception as e:
                        print(f"  [{i+1}/{num_per_task}] {sample_id} — ERROR: {e}")
                        failed += 1
                        time.sleep(2)
                        continue

                    sample = format_training_sample("query_parsing", user_content, output)
                    sample["id"] = sample_id
                    sample["source_jd_id"] = jd["id"]

                    out_f.write(json.dumps(sample, ensure_ascii=False) + "\n")
                    out_f.flush()
                    generated += 1
                    count += 1
                    print(f"  [{i+1}/{num_per_task}] {sample_id} ✓  ({jd['role']} @ {jd['industry']})")
                    time.sleep(delay)

            elif task == "match_explanation":
                if not resumes:
                    print("  No resumes loaded — skipping match_explanation task")
                    continue

                pairs = []
                for _ in range(num_per_task):
                    jd = random.choice(jds)
                    resume = random.choice(resumes)
                    pairs.append((jd, resume))

                for i, (jd, resume) in enumerate(pairs):
                    sample_id = f"me_{jd['id']}_{resume['id']}_{i:04d}"
                    if sample_id in existing_ids:
                        print(f"  [{i+1}/{num_per_task}] {sample_id} — skip (exists)")
                        count += 1
                        continue

                    user_content = build_match_explainer_prompt(jd["text"], resume["text"])
                    messages = get_inference_messages("match_explanation", user_content)

                    try:
                        output = call_claude(client, messages)
                    except Exception as e:
                        print(f"  [{i+1}/{num_per_task}] {sample_id} — ERROR: {e}")
                        failed += 1
                        time.sleep(2)
                        continue

                    sample = format_training_sample("match_explanation", user_content, output)
                    sample["id"] = sample_id
                    sample["source_jd_id"] = jd["id"]
                    sample["source_resume_id"] = resume["id"]

                    out_f.write(json.dumps(sample, ensure_ascii=False) + "\n")
                    out_f.flush()
                    generated += 1
                    count += 1
                    print(f"  [{i+1}/{num_per_task}] {sample_id} ✓")
                    time.sleep(delay)

    print(f"\nDone. Generated: {generated}  Failed/skipped: {failed}")
    print(f"Output: {output_path}")


# ---------------------------------------------------------------
# Batch API (async, 50% cheaper)
# ---------------------------------------------------------------

def run_batch(
    client: anthropic.Anthropic,
    tasks: list[str],
    jds: list[dict],
    resumes: list[dict],
    num_per_task: int,
):
    """
    Submit all requests as a single Batch API job.
    Results are written to data/generated/train_raw.jsonl once the batch completes.

    Claude Batch API docs:
    https://docs.anthropic.com/en/docs/build-with-claude/message-batches
    """
    requests = []

    for task in tasks:
        if task == "query_parsing":
            items = random.choices(jds, k=num_per_task)
            for i, jd in enumerate(items):
                user_content = build_query_parser_prompt(jd["text"])
                messages = get_inference_messages("query_parsing", user_content)
                requests.append({
                    "custom_id": f"qp_{jd['id']}_{i:04d}",
                    "params": {
                        "model": MODEL,
                        "max_tokens": 512,
                        "messages": messages,
                    },
                    "_meta": {"task": "query_parsing", "user_content": user_content, "source_jd_id": jd["id"]},
                })

        elif task == "match_explanation":
            if not resumes:
                print("No resumes — skipping match_explanation in batch")
                continue
            for i in range(num_per_task):
                jd = random.choice(jds)
                resume = random.choice(resumes)
                user_content = build_match_explainer_prompt(jd["text"], resume["text"])
                messages = get_inference_messages("match_explanation", user_content)
                requests.append({
                    "custom_id": f"me_{jd['id']}_{resume['id']}_{i:04d}",
                    "params": {
                        "model": MODEL,
                        "max_tokens": 1024,
                        "messages": messages,
                    },
                    "_meta": {"task": "match_explanation", "user_content": user_content,
                              "source_jd_id": jd["id"], "source_resume_id": resume["id"]},
                })

    if not requests:
        print("No requests to submit.")
        return

    # Separate _meta from API payload
    meta_map = {r["custom_id"]: r.pop("_meta") for r in requests}

    print(f"Submitting batch of {len(requests)} requests...")
    batch = client.messages.batches.create(
        requests=[
            {"custom_id": r["custom_id"], "params": r["params"]}
            for r in requests
        ]
    )
    print(f"Batch ID: {batch.id}")
    print(f"Status: {batch.processing_status}")
    print(f"\nBatch submitted. Poll status with:")
    print(f"  python scripts/distill_data.py --fetch_batch {batch.id}")

    # Save batch metadata for later retrieval
    meta_path = Path(f"data/generated/batch_{batch.id}_meta.jsonl")
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    with open(meta_path, "w") as f:
        for custom_id, meta in meta_map.items():
            f.write(json.dumps({"custom_id": custom_id, **meta}, ensure_ascii=False) + "\n")
    print(f"Batch metadata saved: {meta_path}")


def fetch_batch_results(client: anthropic.Anthropic, batch_id: str):
    """Poll a submitted batch and write results once complete."""
    batch = client.messages.batches.retrieve(batch_id)
    print(f"Batch {batch_id} status: {batch.processing_status}")

    if batch.processing_status != "ended":
        print("Batch not complete yet. Try again later.")
        return

    # Load metadata
    meta_path = Path(f"data/generated/batch_{batch_id}_meta.jsonl")
    meta_map = {}
    if meta_path.exists():
        with open(meta_path) as f:
            for line in f:
                if line.strip():
                    rec = json.loads(line)
                    meta_map[rec["custom_id"]] = rec

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    failed = 0

    with open(OUTPUT_PATH, "a") as out_f:
        for result in client.messages.batches.results(batch_id):
            if result.result.type != "succeeded":
                print(f"  {result.custom_id} — {result.result.type}")
                failed += 1
                continue

            output = result.result.message.content[0].text.strip()
            meta = meta_map.get(result.custom_id, {})
            task = meta.get("task", "query_parsing")
            user_content = meta.get("user_content", "")

            if task == "query_parsing":
                try:
                    json.loads(output)
                except json.JSONDecodeError:
                    failed += 1
                    continue

            sample = format_training_sample(task, user_content, output)
            sample["id"] = result.custom_id
            for k in ("source_jd_id", "source_resume_id"):
                if k in meta:
                    sample[k] = meta[k]

            out_f.write(json.dumps(sample, ensure_ascii=False) + "\n")
            written += 1

    print(f"\nDone. Written: {written}  Failed: {failed}")
    print(f"Output: {OUTPUT_PATH}")


# ---------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate distillation training data via Claude")
    parser.add_argument("--tasks", type=str, default="query_parsing",
                        help="Comma-separated tasks: query_parsing,match_explanation")
    parser.add_argument("--num", type=int, default=1500,
                        help="Samples per task")
    parser.add_argument("--jds", type=str, default="data/jds/all_jds.jsonl")
    parser.add_argument("--resumes", type=str, default="data/resumes/all_resumes.jsonl")
    parser.add_argument("--output", type=str, default=str(OUTPUT_PATH))
    parser.add_argument("--resume", action="store_true",
                        help="Skip samples already in output file")
    parser.add_argument("--batch", action="store_true",
                        help="Use Batch API (async, 50% cheaper)")
    parser.add_argument("--fetch_batch", type=str, default=None,
                        help="Fetch results for a completed batch ID")
    parser.add_argument("--delay", type=float, default=0.3,
                        help="Seconds between API calls (standard mode only)")
    args = parser.parse_args()

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY not set — add it to .env")
    client = anthropic.Anthropic(api_key=api_key)

    # Fetch results for an already-submitted batch
    if args.fetch_batch:
        fetch_batch_results(client, args.fetch_batch)
        return

    tasks = [t.strip() for t in args.tasks.split(",")]
    output_path = Path(args.output)

    jds = load_jds(args.jds)
    print(f"Loaded {len(jds)} JDs")

    resumes = []
    if "match_explanation" in tasks:
        resumes = load_resumes(args.resumes)
        print(f"Loaded {len(resumes)} resumes")

    if args.batch:
        run_batch(client, tasks, jds, resumes, args.num)
    else:
        existing_ids = load_existing_ids(output_path) if args.resume else set()
        if existing_ids:
            print(f"Resuming — {len(existing_ids)} samples already exist")
        run_standard(client, tasks, jds, resumes, args.num, existing_ids, output_path, args.delay)


if __name__ == "__main__":
    main()
